### ISSUE TITLE
CombinedChart with BarChartData cuts the first and last bars in half

### ISSUE THREAD

**Issue by zamith** [danielgindi/ios-charts#323]
Everything works fine apart from the fact that the first and last bars are cut in half, this might be something that is expected, if so, how can I disable it?

Here's how it looks:

<img width="305" alt="screen shot 2015-08-27 at 7 45 10" src="https://cloud.githubusercontent.com/assets/166304/9529792/2cb8599e-4cf4-11e5-9416-3748aef43930.png">

**Comment by liuxuan30** [comment]
By default it should not be half.. I am not sure how much you changed? The code will leave some space for the first and last bar. I never see it on my side. You might need to provide more info. Have you changed any view port/offset properties or transformer matrix, etc. Is it zoomed or something.

You can also try your data with the ChartsDemo code to see if it is reproducible.

**Comment by zamith** [comment]
I haven't changed any viewport things I think, nor should it be zoomed. However, we've decided to go with a linebar, which works fine, so I'm closing this issue.

Sorry about the trouble.

**Comment by liuxuan30** [comment]
Well it never should be half a bar if you just setup the dataSets. If it is a bug (which I doubt), you could help provide some information.

**Comment by zamith** [comment]
Ok, I was able to reproduce it on the Demo. If I comment the setting of the bubbleData, the same behavior occurs:

<img width="432" alt="screen shot 2015-08-28 at 3 31 59" src="https://cloud.githubusercontent.com/assets/166304/9537824/66cda9d6-4d35-11e5-9565-dff1149a1c28.png">

And with the bubbleData:

<img width="432" alt="screen shot 2015-08-28 at 3 32 56" src="https://cloud.githubusercontent.com/assets/166304/9537832/80bb7df0-4d35-11e5-9dd5-053ef259b858.png">

**Comment by liuxuan30** [comment]
Are you using combined chart in your project? How about normal bar chart?

**Comment by zamith** [comment]
Yes, I was using combined chart. The normal bar chart works fine.

**Comment by liuxuan30** [comment]
Ah hah, it's actually a bug. if you don't have bubble chart, it will use another value to determine the chartXMin and chartXMax.

In CombinedChartView -> override func calcMinMax():
```Swift
            if (self.bubbleData !== nil)
            {
                for set in self.bubbleData.dataSets as! [BubbleChartDataSet]
                {
                    let xmin = set.xMin
                    let xmax = set.xMax
                    
                    if (xmin < chartXMin)
                    {
                        _chartXMin = xmin
                    }
                    
                    if (xmax > chartXMax)
                    {
                        _chartXMax = xmax
                    }
                }
            }
            else
            {
//                _chartXMin = 0.0      <--- current in your code
//                _chartXMax = Double(_data.xValCount - 1)      <--- current in your code
                _chartXMin = -0.5   <--- try this
                _chartXMax = Double(_data.xVals.count) - 0.5     <--- try this
            }
```
You could try to use above change, if you want to use combined chart without bubbles. BTW, current combined chart just supports single bar, not grouped (I have a PR #269 for grouped support, but it's still in alpha testing :-)  )

@danielgindi do you know why use 0.0 if no bubble data?

**Comment by zamith** [comment]
Yes, that works. Thanks.

**Comment by reeyan** [comment]
I had the same issue when I upgrade this month. Thanks for the update. Now the issue is gone.

**Comment by danielgindi** [comment]
Fixed thanks to @liuxuan30 :-)

**Comment by arorajatin** [comment]
The fix for it is adjusting the xAxis paddings.

This is my code:

`
let xAxisPadding = 0.45

chartView.xAxis.axisMinimum = -xAxisPadding
chartView.xAxis.axisMaximum = combinedChartData.xMax + xAxisPadding
`

**Comment by vCrespoP** [comment]
Still happening on almost 2018.

@arorajatin you're a HERO, Sir 😍

**Comment by sadaf-behbahani** [comment]
@arorajatin worked for me :) Thanks <3

**Comment by liuxuan30** [comment]
I have an issue seems related to this: https://github.com/danielgindi/Charts/issues/3186. There are some workaround and root cause I found there. feel free to check it out. I didn't come up with a good solution yet

**Comment by milakovicmilosOviva** [comment]
This works in case when you don't have labels on x axis. If you have to print labels on x axis they won't be aligned to rounded values, but will start from -0.5 or -0.45 depending on your implementation.  
`xAxis.centerAxisLabelsEnabled` also can't help.

**Comment by jjatie** [comment]
As this issue is very old, please open a new issue to report any related problems.

**Comment by liuxuan30** [comment]
@jjatie no need, I think we already have the root cause in my #3186.
