### ISSUE TITLE
Recalculate space on label formatting.

### ISSUE THREAD

**Issue by lidgardo** [danielgindi/ios-charts#561]
Hi. I found a little issue which i have been struggling a lot, it seems that if i apply a format on the x-labels the API doesn't recalculate the space in the wit the new format. 

I'm adding a formatter to add an elipsis (...) when the label is more than 7 characters length just like you can see in the image.

<img width="328" alt="screen shot 2015-11-20 at 5 46 00 pm" src="https://cloud.githubusercontent.com/assets/5713880/11314790/a29a4f3a-8fae-11e5-93fa-4d4bf2702170.png">

All the gray area is the barChartView, If i don't use the formatter i got this 

<img width="329" alt="screen shot 2015-11-20 at 5 45 28 pm" src="https://cloud.githubusercontent.com/assets/5713880/11314809/ca73952a-8fae-11e5-84cc-69ba79b50693.png">

The code that i'm using to add the formatter is the following: 

Container class:

```objective-c
ChartXAxis *xAxis = barView.xAxis;
LargeValueFormatter *formatter = [LargeValueFormatter new];
xAxis.valueFormatter = formatter;


```

Formatter class:

```swift
    public func stringForXValue(index: Int, original: String, viewPortHandler: ChartViewPortHandler) -> String {
        
        if original.characters.count > 7 {
            return self.addEllipsis(value: original)
        } else {
            return original
        }
    }
```

As you can see, without the formatter the chart  use in a better way the space, i guess that the problem is that API don't recalculate the bottomContent once that the labels are formatted. I'd like to help with this if you guys can give a little explanations if my diagnosis of the issue is ok and where i can find the code that i need to call to recalculate with the new labels. I guess this could be a great feature.

Thanks in advance. 🤓

**Comment by liuxuan30** [comment]
I think this is related to https://github.com/danielgindi/ios-charts/pull/513. This is how the label is rotated. In the PR there is some explainations how it work.

**Comment by lidgardo** [comment]
The alignment is ok, the problem is that i think that the chart needs to be bigger in the first image, this because the labels are smaller than in the second image just to take advantage of the extra space that we gain adding the ellipsis at the labels.

**Comment by liuxuan30** [comment]
I may understand your point, but still It's a little hard to see the difference of sizes. Are you talking about the height? 

Could you please check the chartView's frame size and the viewPortHandler.contentRect? There is some different size for the whole UIView and the area to draw the chart itself, excluding the axis and axis labels.

**Comment by liuxuan30** [comment]
I may understand your point, but still It's a little hard to see the difference of sizes. Are you talking about the height? 

Could you please check the chartView's frame size and the viewPortHandler.contentRect? There is some different size for the whole UIView and the area to draw the chart itself, excluding the axis and axis labels.

**Comment by liuxuan30** [comment]
I may understand your point, but still It's a little hard to see the difference of sizes. Are you talking about the height? 

Could you please check the chartView's frame size and the viewPortHandler.contentRect? There is some different size for the whole UIView and the area to draw the chart itself, excluding the axis and axis labels.

**Comment by liuxuan30** [comment]
OK so I took a quick look about this, it seems that it does not take the formatter will change the size into account.
In the code where we compute the x axis label size/rotated size, we don't use formatter first. I guess this can be improved, and we also need to consider y axis, because y axis' `requiredSize` does not use formatter as well.

We should apply the formater before we calculate label size, like we may add $ after the profit.

@danielgindi, what do you think? 

```swift
    public func computeAxis(xValAverageLength xValAverageLength: Double, xValues: [String?])
    {
        var a = ""
        
        let max = Int(round(xValAverageLength + Double(_xAxis.spaceBetweenLabels)))
        
        for (var i = 0; i < max; i++)
        {
            a += "h"
        }
        
        let widthText = a as NSString
        
        let labelSize = widthText.sizeWithAttributes([NSFontAttributeName: _xAxis.labelFont])
        
        let labelWidth = labelSize.width
        let labelHeight = labelSize.height
        
        let labelRotatedSize = ChartUtils.sizeOfRotatedRectangle(labelSize, degrees: _xAxis.labelRotationAngle)
        
        _xAxis.labelWidth = labelWidth
        _xAxis.labelHeight = labelHeight
        _xAxis.labelRotatedWidth = labelRotatedSize.width
        _xAxis.labelRotatedHeight = labelRotatedSize.height
        
        _xAxis.values = xValues
    }
```
```swift
    public func requiredSize() -> CGSize
    {
        let label = getLongestLabel() as NSString
        var size = label.sizeWithAttributes([NSFontAttributeName: labelFont])
        size.width += xOffset * 2.0
        size.height += yOffset * 2.0
        size.width = max(minWidth, min(size.width, maxWidth > 0.0 ? maxWidth : size.width))
        return size
    }
```

**Comment by lidgardo** [comment]
Exactly! Thats the problem, I fixed in a dirty way because i need to implement my custom formatter in the ChartData object and in the x-Axis, I implemented the same logic for the y-Axis too. let me explain.

The functions which is in charge to calculate the space is the xValsAverageLength, this one needs to apply the format to the labels that why i added the format to the data object.

```swift
    // calculates the average length (in characters) across all x-value strings
    internal func calcXValAverageLength()
    {
        if (_xVals.count == 0)
        {
            _xValAverageLength = 1
            return
        }
        
        var sum = 1
        
        for (var i = 0; i < _xVals.count; i++)
        {
            let label = _xVals[i]! as String
            //Apply the format
            let formattedLabel = _xValsValueFormatter.stringForXValue(i, original: label) ?? label
            
            sum += _xVals[i] == nil ? 0 : (formattedLabel).characters.count
        }   
        _xValAverageLength = Double(sum) / Double(_xVals.count)
    }
```

I'm using the same formatter that i pass to the x-Axis because this is the one which display the labels in the chart, If you have any idea or help how to implement this i'd love to contribute with you guys. 

Fort the y-Axis i did the same, i guess that this is a clean implementation. 

```swift
    /// formatter for the x-Values
    public var yValsValueFormatter: ChartXAxisValueFormatter?{
        get{
            return _yValsValueFormatter
        }
        set{
            _yValsValueFormatter = newValue ?? ChartDefaultXAxisValueFormatter()
        }
    }
```
```swift
    /// - returns: the formatted y-label at the specified index. This will either use the auto-formatter or the custom formatter (if one is set).
    public func getFormattedLabel(index: Int) -> String
    {
        if (index < 0 || index >= entries.count)
        {
            return ""
        }
        
        let formattedValue = _yValsValueFormatter.stringForXValue(index, original: (valueFormatter ?? _defaultValueFormatter).stringFromNumber(entries[index])!)
        
        return formattedValue
    }
```

In this case i'm still using your number formatter the problem was that i needed a non standard format for the y-Axis  ( 1000 = 1K, 1000000 = 1M ) that why i sued a custom formatter. I think that this feature also need to be in the iOS api not just un the Android one. 

Thanks in advance 🤓

**Comment by liuxuan30** [comment]
if possible, follow the code style and not the 'dirty' way to create a PR :)

**Comment by hetpin** [comment]
@lidgardo Can you explain in details how to customize Y-axis. Honestly, I tried to read your comments above, but still can not implement.

I worked with ChartYAxisValueFormatter Android version. I'm porting my App to IOS, but I can not find ChartYAxisValueFormatter IOS version. I'm not senior on ios dev, can you help. Pls.

**Comment by liuxuan30** [comment]
@hetpin if you are looking for y axis formater, it is here:

```swift
    /// the formatter used to customly format the y-labels
    public var valueFormatter: NSNumberFormatter?
    
    /// the formatter used to customly format the y-labels
    internal var _defaultValueFormatter = NSNumberFormatter()`
```

**Comment by lidgardo** [comment]
Hi @hetpin as @liuxuan30 said those are the properties to format the Y-Axis, you need to take in consideration that this are only functionals to standard number format, if this is your case that property will be useful. if not You i'll need to implement your formatter extends from the class


```swift 
ChartXAxisValueFormatter
```

Now according my comments above all of them were to fix the process of calculate the space. I'm working on a pull request to add this enhancement. If you have doubts about the custom formatter I can explain you better, in other case you can use the valueFormatter property which is already there. 

Sorry for the late response. 
Cheers!

**Comment by hetpin** [comment]
Thanks for help, I ended up with a simple customization of NSNumberFormatter. In short, I subclassed NSNumberFormatter and override two methods: - (id)init; and - (NSString *)stringForObjectValue:(id const)aObj; Simple and effective.
Thanks.

**Comment by liuxuan30** [comment]
oops. the original issue is not solved yet.

**Comment by danielgindi** [comment]
This is a problematic one, requiring some changes to the api.

@PhilJay what do you think about passing the `viewPortHandler` to `computeAxis` so we can pass it to `getLongestLabel` so we can pass it to the X axis formatter?

**Comment by danielgindi** [comment]
@PhilJay ?

**Comment by PhilJay** [comment]
Sorry, didn't see this.
Looks like a big issue. I will look into it tomorrow!

**Comment by danielgindi** [comment]
I'm not sure, but I think that this one is also solved by Charts 3.0, am I right?

**Comment by zigdanis** [comment]
`open func getLongestLabel() -> String` called for only visible chart area. 
So `open func computeSize()` doesn't fit all xAxis values when user scrolling bar chart.
I would be happy to have some way to calculate bottom xAxis offset that will handle all `dataSet` values😀
![example](https://cloud.githubusercontent.com/assets/1284116/19389415/fd74576e-9234-11e6-8056-eaeded32bf19.png)

**Comment by elchris78** [comment]
Hey guys,

I didn't get what the solution was! I'm still having the same spacing problem, any solution?

**Comment by romrell4** [comment]
I believe I'm having the same issue, but with some additional details:
I've got a LineChart with rotated bottom X values. When it first draws, it seems to not take into account the extra rotated value height necessary. However, when I come back and it redraws, it does...
https://github.com/danielgindi/Charts/assets/15692420/e6eb3b58-b637-4b44-b417-a4413d5f78fd

Any idea what race case could be causing the initial draw to not have the correct height?
