### ISSUE TITLE
How to remove the edge's border of time line chart filled shaped

### ISSUE THREAD

**Issue by gabetse** [danielgindi/ios-charts#881]
![snip20160325_1](https://cloud.githubusercontent.com/assets/659130/14058525/9bb3d39a-f35d-11e5-937a-23b21678824b.png)

How to remove the fill shape's edges borders , it's unnecessary in my case, thank you

**Comment by liuxuan30** [comment]
update your library. It should be fixed in https://github.com/danielgindi/ios-charts/issues/747

**Comment by gabetse** [comment]
![snip20160328_13](https://cloud.githubusercontent.com/assets/659130/14080760/9b952dd6-f539-11e5-8db9-129de9b7a92e.png)

It's still shown and version is 2.2.3

**Comment by gabetse** [comment]
I install through pods

**Comment by liuxuan30** [comment]
guess you have to wait if 747 is not released to pod yet.
